help:
	@echo "Run make build to compile into 'build/message_box' folder."


.PHONY: build help

build:
	oooscript compile --embed --config "$(PWD)/config.json" --embed-doc "$(PWD)/msgbox.odt" --build-dir "build/message_box"
