help:
	@echo "Run make build to compile into 'build/input_box' folder."


.PHONY: build help

build:
	oooscript compile --embed --config "$(PWD)/config.json" --embed-doc "$(PWD)/inputbox.odt" --build-dir "build/input_box"
