help:
	@echo "Run make build to compile into 'build/BasicCounter' folder."


.PHONY: build help

build:
	oooscript compile --embed --config "$(PWD)/config.json" --embed-doc "$(PWD)/BasicCounter.ods" --build-dir "build/BasicCounter"
